### ISSUE TITLE
Better support for Paper servers

### ISSUE THREAD

**Issue by hcshires** [hcshires/DSMRealTime#4]
Currently, paper servers cannot properly run the plugin. An example warning is included:

```[08:58:29 WARN]: [DSMRealTime] Task #520 for DSMRealTime v1.0.0 generated an exception
java.lang.NullPointerException: null
at org.projectdsm.dsmrealtime.DSMRealTime.setTime(DSMRealTime.java:149) ~[?:?]
at org.projectdsm.dsmrealtime.DSMRealTime.lambda$onEnable$0(DSMRealTime.java:261) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-594]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-594]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1423) ~[patched_1.16.5.jar:git-Paper-594]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.16.5.jar:git-Paper-594]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1338) ~[patched_1.16.5.jar:git-Paper-594]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1126) ~[patched_1.16.5.jar:git-Paper-594]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-594]
at java.lang.Thread.run(Thread.java:834) [?:?]```

**Comment by hcshires** [comment]
# DSMRealTime - Sync your Spigot Server to your real time and weather
# Please config your DSMRealTime plugin using the fields below:
# 
# Setup Instructions can be found here: https://github.com/hcshires/DSMRealTime/wiki/Installation

SyncTime: true
SyncWeather: true
Debug: true
World: B-G
Timezone: Europe/Berlin
APIKey: API_KEY
Location: Cologne, DE
