### ISSUE TITLE
Help: failed to get description

### ISSUE THREAD

**Issue by artemsnite** [hcshires/DSMRealTime#6]
Error: `[13:11:30 ERROR]: Could not load 'plugins/DSMRealTime.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:158) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:136) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:318) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:222) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1620]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_312]
        at java.util.zip.ZipFile.<init>(ZipFile.java:228) ~[?:1.8.0_312]
        at java.util.zip.ZipFile.<init>(ZipFile.java:157) ~[?:1.8.0_312]
        at java.util.jar.JarFile.<init>(JarFile.java:171) ~[?:1.8.0_312]
        at java.util.jar.JarFile.<init>(JarFile.java:135) ~[?:1.8.0_312]
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:146) ~[patched_1.12.2.jar:git-Paper-1620]
        ... 5 more`

**Comment by artemsnite** [comment]
Also your discord link doesnt work

**Comment by artemsnite** [comment]
sry found the soution

**Comment by hcshires** [comment]
Sorry, I didn't see this. Here's the link to our discord: https://discord.gg/wJUeVBK
Where did you see it didn't work?
